version: "3.9"

services:
  neo4j:
    restart: always
    image: neo4j:5.1.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - .export/neo4j/data:/data
      - .export/neo4j/var/lib/neo4j/conf:/var/lib/neo4j/conf
      - .export/neo4j/logs:logs
      - .export/neo4j/var/lib/neo4j/import:/var/lib/neo4j/import
      - .export/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - neo4j
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend